// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5oH1L8yQdNuEsUEfwB71-ot7liDKqc-I',
    appId: '1:1097117992472:web:e8ff4790dd8f3d0319a56d',
    messagingSenderId: '1097117992472',
    projectId: 'auditorpalsfyp',
    authDomain: 'auditorpalsfyp.firebaseapp.com',
    storageBucket: 'auditorpalsfyp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaBu1ChrihZ6N-7yAzb9GGwnuz7Dq7s_M',
    appId: '1:1097117992472:android:0eea0d0a6dce0bff19a56d',
    messagingSenderId: '1097117992472',
    projectId: 'auditorpalsfyp',
    storageBucket: 'auditorpalsfyp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHuhhCfM7cx7k9zIbKZq4FCaYgq4ATCmg',
    appId: '1:1097117992472:ios:f33593605fada3f619a56d',
    messagingSenderId: '1097117992472',
    projectId: 'auditorpalsfyp',
    storageBucket: 'auditorpalsfyp.appspot.com',
    iosClientId: '1097117992472-6i7usjpnihk9346nt1hjoln16dvvvook.apps.googleusercontent.com',
    iosBundleId: 'com.example.auditorpal',
  );
}
